# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'websocket-app-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Starscream', '~> 3.0.4'

  # Pods for websocket-app-ios

end
